server:
  port: 8080
  servlet:
    context-path: /

spring:
  resources:
    #指定静态资源路径，默认为classpath:[/META-INF/resources/,/resources/, /static/, /public/]以及context:/
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/}

  #热部署--静态资源立即生效
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true

  #热部署生效
  devtools:
    restart:
      enabled: true

logging:
  level:
    learning: info

  #  logging:
  #    level:
  #      root: info
  #      com.bestvike: debug
  #      org.springframework.security: warn
  # 默认日志文件名
  # file: log
  # 默认日志路径
  # path: ./log
# logback.xml路径，默认为classpath:logback.xml
# config: ./logback.xml
